import type { Metadata } from "next";
import { Inter,  } from "next/font/google";
import {NuqsAdapter} from"nuqs/adapters/next/app";

import "./globals.css";

const inter =   Inter({
  subsets:["latin"],
})
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/convex-client-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={inter.className}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            {/* <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn> */}
          </header>
          <NuqsAdapter>
            <ConvexClientProvider>

           
          {children}
          
           </ConvexClientProvider>
          </NuqsAdapter>
        </body>
      </html>
    </ClerkProvider>
  );
}
